name: brightski_task
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.5
  flutter_bloc: ^8.1.3
  http: ^0.13.1
  get_it: ^7.1.0
  dartz: ^0.10.1
  shared_preferences: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
